spring.application.name=demoauth

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5435/demoauth}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=trueperties.hibernate.format_sql=trueerties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/demo-realm}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost:8081/realms/demo-realm/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.distribution.percentiles-histogram.http.server.requests=true

authorization.cache.enabled=true



